version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: backend
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_DEBUG: false
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    container_name: frontend
    depends_on:
      - backend
    env_file:
      - .env
    ports:
      - "80:80"

volumes:
  pgdata: 